apiVersion: v1
kind: ReplicationController
metadata:
  name: helloworld-pod
  labels:
    app: helloworld-pod
    type: api
spec:
  replicas: 2

  template:
    metadata:
      name: helloworld-pod

      labels:
        app: helloworld-pod
        type: api

    spec:
      containers:
        - name: helloworld-pod
          image: helloworldapi:latest
          ports:
            - containerPort: 80
